input {
  tcp {
    port => 5001
    codec => json
  }
}

filter {
  if [requestId] {
    mutate {
      add_field => { "correlation_id" => "%{requestId}" }
    }
  }

  mutate {
    add_field => { "service" => "ecotrack-api" }
    add_field => { "environment" => "${NODE_ENV:development}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ecotrack-api-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
