import type { InternalEventSchemaDefinition } from './internal-events.contracts.js';

export const INTERNAL_EVENT_SCHEMAS: readonly InternalEventSchemaDefinition[] = [
  {
    subject: 'iot.ingestion.request',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Inbound HTTP payload accepted by the IoT ingestion controller.',
    fields: [
      { name: 'deviceUid', type: 'string', required: true },
      { name: 'measuredAt', type: 'timestamp', required: true },
      { name: 'fillLevelPercent', type: 'integer', required: true },
      { name: 'temperatureC', type: 'integer', required: false },
      { name: 'batteryPercent', type: 'integer', required: false },
      { name: 'signalStrength', type: 'integer', required: false },
      { name: 'measurementQuality', type: 'string', required: false, hasDefault: true },
      { name: 'idempotencyKey', type: 'string', required: false },
    ],
  },
  {
    subject: 'iot.ingestion.staged',
    version: 'v1',
    compatibility: 'BACKWARD',
    description: 'Durable staged-event contract persisted in iot.ingestion_events.',
    fields: [
      { name: 'id', type: 'uuid', required: true },
      { name: 'deviceUid', type: 'string', required: true },
      { name: 'routingKey', type: 'string', required: true },
      { name: 'shardId', type: 'integer', required: true },
      { name: 'producerName', type: 'string', required: true },
      { name: 'producerTransactionId', type: 'uuid', required: true },
      { name: 'traceparent', type: 'string', required: false },
      { name: 'tracestate', type: 'string', required: false },
    ],
  },
  {
    subject: 'iot.measurement.validated',
    version: 'v1',
    compatibility: 'BACKWARD',
    description: 'Validated internal event emitted by the ingestion worker.',
    fields: [
      { name: 'sourceEventId', type: 'uuid', required: true },
      { name: 'deviceUid', type: 'string', required: true },
      { name: 'routingKey', type: 'string', required: true },
      { name: 'shardId', type: 'integer', required: true },
      { name: 'measuredAt', type: 'timestamp', required: true },
      { name: 'fillLevelPercent', type: 'integer', required: true },
      { name: 'measurementQuality', type: 'string', required: true },
      { name: 'warningThreshold', type: 'integer', required: false },
      { name: 'criticalThreshold', type: 'integer', required: false },
    ],
  },
  {
    subject: 'iot.measurement.validated',
    version: 'v1.1',
    compatibility: 'BACKWARD',
    description:
      'Validated internal event emitted by the ingestion worker with optional ingestion-source metadata.',
    fields: [
      { name: 'sourceEventId', type: 'uuid', required: true },
      { name: 'deviceUid', type: 'string', required: true },
      { name: 'routingKey', type: 'string', required: true },
      { name: 'shardId', type: 'integer', required: true },
      { name: 'measuredAt', type: 'timestamp', required: true },
      { name: 'fillLevelPercent', type: 'integer', required: true },
      { name: 'measurementQuality', type: 'string', required: true },
      { name: 'warningThreshold', type: 'integer', required: false },
      { name: 'criticalThreshold', type: 'integer', required: false },
      { name: 'ingestionSource', type: 'string', required: false, hasDefault: true },
    ],
  },
  {
    subject: 'iot.validated.delivery',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Durable delivery envelope queued for internal validated-event consumers.',
    fields: [
      { name: 'consumerName', type: 'string', required: true },
      { name: 'validatedEventId', type: 'uuid', required: true },
      { name: 'eventName', type: 'string', required: true },
      { name: 'routingKey', type: 'string', required: true },
      { name: 'shardId', type: 'integer', required: true },
      { name: 'traceparent', type: 'string', required: false },
      { name: 'tracestate', type: 'string', required: false },
    ],
  },
  {
    subject: 'iot.measurement.rollup.10m',
    version: 'v1',
    compatibility: 'BACKWARD',
    description: 'Derived 10-minute rich-measurement rollup persisted for fast reads.',
    fields: [
      { name: 'validatedEventId', type: 'uuid', required: true },
      { name: 'deviceUid', type: 'string', required: true },
      { name: 'windowStart', type: 'timestamp', required: true },
      { name: 'windowEnd', type: 'timestamp', required: true },
      { name: 'measurementCount', type: 'integer', required: true },
      { name: 'averageFillLevelPercent', type: 'integer', required: true },
      { name: 'fillLevelDeltaPercent', type: 'integer', required: true },
      { name: 'sensorHealthScore', type: 'integer', required: true },
    ],
  },
  {
    subject: 'collections.tour.scheduled',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Collection command-side event emitted when a tour is scheduled.',
    fields: [
      { name: 'tourId', type: 'uuid', required: true },
      { name: 'name', type: 'string', required: true },
      { name: 'scheduledFor', type: 'timestamp', required: true },
      { name: 'zoneId', type: 'uuid', required: false },
      { name: 'assignedAgentId', type: 'uuid', required: false },
      { name: 'stopCount', type: 'integer', required: true },
    ],
  },
  {
    subject: 'collections.tour.updated',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Collection command-side event emitted when a tour definition changes.',
    fields: [
      { name: 'tourId', type: 'uuid', required: true },
      { name: 'updatedFields', type: 'json', required: true },
      { name: 'stopCount', type: 'integer', required: true },
    ],
  },
  {
    subject: 'collections.tour.started',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Collection command-side event emitted when a tour starts.',
    fields: [
      { name: 'tourId', type: 'uuid', required: true },
      { name: 'startedAt', type: 'timestamp', required: true },
      { name: 'firstActiveStopId', type: 'uuid', required: false },
    ],
  },
  {
    subject: 'collections.stop.validated',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Collection command-side event emitted when a tour stop is validated.',
    fields: [
      { name: 'tourId', type: 'uuid', required: true },
      { name: 'tourStopId', type: 'uuid', required: true },
      { name: 'containerId', type: 'uuid', required: true },
      { name: 'collectedAt', type: 'timestamp', required: true },
      { name: 'volumeLiters', type: 'integer', required: false },
      { name: 'nextStopId', type: 'uuid', required: false },
    ],
  },
  {
    subject: 'collections.tour.completed',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Collection command-side event emitted when a tour reaches terminal completion.',
    fields: [
      { name: 'tourId', type: 'uuid', required: true },
      { name: 'completedAt', type: 'timestamp', required: true },
      { name: 'completedStopCount', type: 'integer', required: true },
    ],
  },
  {
    subject: 'collections.tour.cancelled',
    version: 'v1',
    compatibility: 'FULL',
    description: 'Collection command-side event emitted when a tour is cancelled.',
    fields: [
      { name: 'tourId', type: 'uuid', required: true },
      { name: 'cancelledAt', type: 'timestamp', required: true },
      { name: 'reason', type: 'string', required: false },
    ],
  },
  {
    subject: 'analytics.zone.aggregate.10m',
    version: 'v1',
    compatibility: 'BACKWARD',
    description: 'Derived 10-minute zone aggregate read-model event for future externalization.',
    fields: [
      { name: 'zoneId', type: 'uuid', required: true },
      { name: 'windowStart', type: 'timestamp', required: true },
      { name: 'windowEnd', type: 'timestamp', required: true },
      { name: 'measurementsCount', type: 'integer', required: true },
      { name: 'averageFillLevelPercent', type: 'integer', required: true },
      { name: 'minFillLevelPercent', type: 'integer', required: true },
      { name: 'maxFillLevelPercent', type: 'integer', required: true },
      { name: 'highFillCount', type: 'integer', required: true },
      { name: 'trendSlopePerHour', type: 'integer', required: true },
    ],
  },
] as const;
