apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: ecotrack-api-logs-*
      timeField: "@timestamp"
      interval: Daily
      esVersion: "8.12.0"
      logMessageField: msg
      logLevelField: level
    editable: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
